travis:
  secure:
    BINSTAR_TOKEN: WrBgt65xNvBr3uzWuXUKxv6KEn7QrDKRW2WemAVvZfq2HLg4E4G9eQtnueRTAmATns8nUxUnoOB8SmySBc+B0MhL5dy6ebwM0hRHlo7zKiKPWAYN7NJq1gmr/n7BIZI0DpZecfV3VP2+Sp6cDEXyaE6Dk24DOwGsVgbUXDArZ3QK5DtvO6gWxDdB+WjkJQ/tKAXX68kxuJa1ItcmCiX0VUC49Z7j/1eg+OOlxIcTP4LDPoiKH5BmRceiMW65LveekvBaaT50sDwWI2/RMuINpSiusqHfWsEM+97yzicLsroOrRNjzOHCcAp8KB4iYO+nkIrQzyvMN0v0RE6L45MwCU/qmhI65Wf4vhGOs07Gio3QMBVRxEu5nHlcxAXV6GYV9JKVA2ACOVfFewqBiukBMO/pqAy3Wmm8+zT+RMM9sYm67QUKYmPqRO+jyMqt6xrbCbKS30BGw0VIKcJ7hGRzsGUFHL3JNjNTmzPzHZwxyXirHfdVSRlZfZgrcy9xh50ctsqzTt6yQm++QX6jRgSu8W0iHIodvV06frmzBr9mmg/h3QqVd6++oY0iHa5aTVBWLaJdra3rIGF+e9ps5kaw71KdWD6A0fcKO9T2X6PJQ49/wnHoX51jI/lmTQEKzpYFyUD7zC4whETKgO9Iua6TUuzZxAWTRm1ilPOp2bwNQRo=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
